/* global document */
export default ({
  feelsLikeText: document.querySelector('.current__weather-feels > span:nth-child(1)'),
  windText: document.querySelector('.current__weather-wind > span:nth-child(1)'),
  humidityText: document.querySelector('.current__weather-humidity > span:nth-child(1)'),
  searchInputText: document.querySelector('.search-input'),
  searchButtonText: document.querySelector('.search-button'),
  latitudeText: document.querySelector('.current__latitude > span:nth-child(1)'),
  longitudeText: document.querySelector('.current__longtitude > span:nth-child(1)'),

  currentCity: document.querySelector('.current__city'),
  currentDegrees: document.querySelector('.current__degrees > span'),
  currentWeatherIcon: document.querySelector('.current__weather-icon'),
  currentWeatherDesc: document.querySelector('.current__weather-description'),
  currentFeelsLike: document.querySelector('.current__weather-feels > span:nth-child(2)'),
  currentWind: document.querySelector('.current__weather-wind > span:nth-child(2)'),
  currentHumidity: document.querySelector('.current__weather-humidity > span:nth-child(2)'),

  firstDayTitle: document.querySelector('.first-forecast-day-title'),
  firstDayDegrees: document.querySelector('.first-forecast-day-degrees > span'),
  firstDayIcon: document.querySelector('.first-forecast-day-icon'),
  secondDayTitle: document.querySelector('.second-forecast-day-title'),
  secondDayDegrees: document.querySelector('.second-forecast-day-degrees > span'),
  secondDayIcon: document.querySelector('.second-forecast-day-icon'),
  thirdDayTitle: document.querySelector('.third-forecast-day-title'),
  thirdDayDegrees: document.querySelector('.third-forecast-day-degrees > span'),
  thirdDayIcon: document.querySelector('.third-forecast-day-icon'),

  currentWeekDay: document.querySelector('.current__weekday'),
  currentDay: document.querySelector('.current__monthday'),
  currentMonth: document.querySelector('.current__month'),
  currentTime: document.querySelector('.current__time'),
  currentTimezone: document.querySelector('.current__timezone'),
  firstWeekDay: document.querySelector('.first-forecast-day-title'),
  secondWeekDay: document.querySelector('.second-forecast-day-title'),
  thirdWeekDay: document.querySelector('.third-forecast-day-title'),

  backgroundImage: document.querySelector('.background-image'),
  queryLoader: document.querySelector('.query-loader-body'),
});
